### ISSUE TITLE
Fatals and deprecation warnings in 1.39

### ISSUE THREAD

**Issue by jdlrobson** [Universal-Omega/Monaco#14]
There are various breaking changes in 1.39 that break this Monaco port.

```
 Error: Call to undefined method OutputPage::addModuleScripts()
```

I tried to fix a few of the easier ones, but then ran into a bunch of deprecation warnings.

```

Warning: foreach() argument must be of type array|object, null given in /Users/jrobson/git/core/includes/skins/SkinTemplate.php on line 801

Warning: foreach() argument must be of type array|object, null given in /Users/jrobson/git/core/includes/skins/SkinTemplate.php on line 801

Deprecated: Use of Skin::addToBodyAttributes method to add body attributes was deprecated in MediaWiki 1.35. [Called from SkinTemplate::prepareQuickTemplate in /Users/jrobson/git/core/includes/skins/SkinTemplate.php at line 384] in /Users/jrobson/git/core/includes/debug/MWDebug.php on line 381

Deprecated: Use of QuickTemplate::(get/html/text/haveData) with parameter `headelement` was deprecated in MediaWiki 1.39. [Called from QuickTemplate::html in /Users/jrobson/git/core/includes/skins/QuickTemplate.php at line 168] in /Users/jrobson/git/core/includes/debug/MWDebug.php on line 381
```

I've marked the skin as unstable on https://www.mediawiki.org/w/index.php?title=Skin:Monaco for now. Let me know how I can help!

**Comment by Universal-Omega** [comment]
I'm kinda confused, the first fatal you mentioned has been fixed since I first took over this, and ported it. https://github.com/Universal-Omega/Monaco/commit/ab75c211a2d78219b9f0a5ee407d51772c6eb7e0 fixed at least that, amongst hundreds of other things, so it's possible it fixed it all still?

**Comment by jdlrobson** [comment]
Apologies, it looks like my local git is associated with https://github.com/Beleggrodion/monaco-port.git presumably the precursor to this one. When I switch to yours, I still get fatals but different ones.

Above patch should fix those. There are still some deprecation warning messages, however (`<b>Warning</b>:  foreach() argument must be of type array|object, null given in <b>/Users/jrobson/git/core/includes/skins/SkinTemplate.php</b> on line <b>801</b><br />`) - this usually indicates unsupported modification to the sidebar.

Thank you for keeping this skin maintained <3

**Comment by Universal-Omega** [comment]
Thank you!
